name: ewind

channels:
- defaults

dependencies:
  - python==3.4
  - numpy==1.10.4
  - scipy==0.17.1
  - pandas==0.17.1 
  - statsmodels==0.6.1
  - patsy=0.4.1
  - matplotlib==1.5.0
  - seaborn==0.6.0
  - ipython==5.1.0
  - notebook==4.3.1
  - nbconvert==4.2.0
  - nbformat==4.2.0

  - pip:
    - tabulate==0.8.1
    - watermark==1.5.0
